// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: I_Image_grpc.proto
#ifndef GRPC_I_5fImage_5fgrpc_2eproto__INCLUDED
#define GRPC_I_5fImage_5fgrpc_2eproto__INCLUDED

#include "I_Image_grpc.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace I_Image_grpc {

class I_Image final {
 public:
  static constexpr char const* service_full_name() {
    return "I_Image_grpc.I_Image";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status get_image(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in& request, ::I_Image_grpc::I_Image_out* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::I_Image_grpc::I_Image_out>> Asyncget_image(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::I_Image_grpc::I_Image_out>>(Asyncget_imageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::I_Image_grpc::I_Image_out>> PrepareAsyncget_image(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::I_Image_grpc::I_Image_out>>(PrepareAsyncget_imageRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void get_image(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in* request, ::I_Image_grpc::I_Image_out* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void get_image(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in* request, ::I_Image_grpc::I_Image_out* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void get_image(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in* request, ::I_Image_grpc::I_Image_out* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::I_Image_grpc::I_Image_out>* Asyncget_imageRaw(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::I_Image_grpc::I_Image_out>* PrepareAsyncget_imageRaw(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status get_image(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in& request, ::I_Image_grpc::I_Image_out* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::I_Image_grpc::I_Image_out>> Asyncget_image(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::I_Image_grpc::I_Image_out>>(Asyncget_imageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::I_Image_grpc::I_Image_out>> PrepareAsyncget_image(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::I_Image_grpc::I_Image_out>>(PrepareAsyncget_imageRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void get_image(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in* request, ::I_Image_grpc::I_Image_out* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void get_image(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in* request, ::I_Image_grpc::I_Image_out* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void get_image(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in* request, ::I_Image_grpc::I_Image_out* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::I_Image_grpc::I_Image_out>* Asyncget_imageRaw(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::I_Image_grpc::I_Image_out>* PrepareAsyncget_imageRaw(::grpc::ClientContext* context, const ::I_Image_grpc::I_Image_in& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_get_image_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status get_image(::grpc::ServerContext* context, const ::I_Image_grpc::I_Image_in* request, ::I_Image_grpc::I_Image_out* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_get_image : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_get_image() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_get_image() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_image(::grpc::ServerContext* /*context*/, const ::I_Image_grpc::I_Image_in* /*request*/, ::I_Image_grpc::I_Image_out* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_image(::grpc::ServerContext* context, ::I_Image_grpc::I_Image_in* request, ::grpc::ServerAsyncResponseWriter< ::I_Image_grpc::I_Image_out>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_get_image<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_get_image : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_get_image() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::I_Image_grpc::I_Image_in, ::I_Image_grpc::I_Image_out>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::I_Image_grpc::I_Image_in* request, ::I_Image_grpc::I_Image_out* response) { return this->get_image(context, request, response); }));}
    void SetMessageAllocatorFor_get_image(
        ::grpc::experimental::MessageAllocator< ::I_Image_grpc::I_Image_in, ::I_Image_grpc::I_Image_out>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::I_Image_grpc::I_Image_in, ::I_Image_grpc::I_Image_out>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_get_image() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_image(::grpc::ServerContext* /*context*/, const ::I_Image_grpc::I_Image_in* /*request*/, ::I_Image_grpc::I_Image_out* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* get_image(
      ::grpc::CallbackServerContext* /*context*/, const ::I_Image_grpc::I_Image_in* /*request*/, ::I_Image_grpc::I_Image_out* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* get_image(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::I_Image_grpc::I_Image_in* /*request*/, ::I_Image_grpc::I_Image_out* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_get_image<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_get_image<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_get_image : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_get_image() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_get_image() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_image(::grpc::ServerContext* /*context*/, const ::I_Image_grpc::I_Image_in* /*request*/, ::I_Image_grpc::I_Image_out* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_get_image : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_get_image() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_get_image() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_image(::grpc::ServerContext* /*context*/, const ::I_Image_grpc::I_Image_in* /*request*/, ::I_Image_grpc::I_Image_out* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestget_image(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_get_image : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_get_image() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->get_image(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_get_image() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status get_image(::grpc::ServerContext* /*context*/, const ::I_Image_grpc::I_Image_in* /*request*/, ::I_Image_grpc::I_Image_out* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* get_image(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* get_image(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_get_image : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_get_image() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::I_Image_grpc::I_Image_in, ::I_Image_grpc::I_Image_out>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::I_Image_grpc::I_Image_in, ::I_Image_grpc::I_Image_out>* streamer) {
                       return this->Streamedget_image(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_get_image() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status get_image(::grpc::ServerContext* /*context*/, const ::I_Image_grpc::I_Image_in* /*request*/, ::I_Image_grpc::I_Image_out* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedget_image(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::I_Image_grpc::I_Image_in,::I_Image_grpc::I_Image_out>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_get_image<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_get_image<Service > StreamedService;
};

}  // namespace I_Image_grpc


#endif  // GRPC_I_5fImage_5fgrpc_2eproto__INCLUDED
